{{- if not .Values.existingSecret -}}
{{- if not .Values.jwtSecret -}}
{{- fail "launchpad: you must set either .Values.jwtSecret (e.g. --set jwtSecret=$(openssl rand -hex 32)) or .Values.existingSecret" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "launchpad.fullname" . }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
type: Opaque
stringData:
  LAUNCHPAD_JWT_SECRET: {{ .Values.jwtSecret | quote }}
{{- end -}}
